#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set o=pipefail

APPNAME="$(hostname)/GoAccess"

if ! [[ -n "$WP_GOACCESS" ]]
then
 echo "[$APPNAME][$(date)] WP_GOACCESS not set in docker-compose.yml. Aborting.."
 sleep infinity
 exit 0
fi

echo "[$APPNAME][$(date)] Started as an s6 service"
/usr/bin/goaccess -f /tmp/access.log -o /var/run/nginx/html/$WP_GOACCESS_FILE --real-time-html -a --ws-url=wss://$SSL_DOMAIN/goaccesswebsocket --port 7891 --db-path /tmp
sleep 10
