#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/GoAccess"

if ! [[ -n "$WP_GOACCESS" ]]
then
 echo "[$APPNAME][$(date)] WP_GOACCESS not set in docker-compose.yml. Aborting.."
 sleep infinity
 exit 0
fi

echo "[$APPNAME][$(date)] Started as an s6 service"

#while true
#do
#  if ! pgrep goaccess > /dev/null;
#  then
    echo "[$APPNAME][$(date)] Restarting GoAccess."
#    /usr/bin/goaccess -f /tmp/access.log -o /var/run/nginx/html/$WP_GOACCESS_FILE --real-time-html -a --daemonize --ws-url=wss://127.0.0.1/goaccesswebsocket --port 7891 --db-path /tmp
#  else
#    echo "runs"
#  fi
sleep 10
#done

