version: '3.8'

services:
  webproxy:
    image: kx1t/webproxy
    tty: true
    container_name: webproxy
    hostname: webproxy
    restart: always
    ports:
      - 8099:80
      - 443:443
    environment:
      #
      # if AUTOGENERATE is set to ON, it will automatically create a config based on the REVPROXY and REDIRECT parameters below
      # if it is set to OFF, you should map the volume as shown in the "volumes" section below, and you can edit the "locations.conf" file in that directory
      - AUTOGENERATE=ON
      # ----------------------------------------------------------------------------------------
      # REVPROXY has the following format:
      #     urltarget|proxytarget
      # For example, for REVPROXY=readsb|http://10.0.0.191:8080,
      # a user browing to http://mydomain/readsb will be proxied to http://10.0.0.191:8080
      # The user's browser will *never* see the internal IP address.
      # Note - both the urltarget and the destination must be URLs or directories, and cannot be
      # a file name
      - REVPROXY=
                 readsb|http://10.0.0.191:8080,
                 piaware|http://10.0.0.191:8081,
                 tar1090|http://10.0.0.191:8082,
                 planefence|http://10.0.0.191:8083,
                 planefinder|http://10.0.0.191:8086,
                 ajax|http://10.0.0.191:8086/ajax,
                 graphs|http://10.0.0.191:8080/graphs,
                 radar|http://10.0.0.191:8080/radar,
                 acarshub|http://10.0.0.188:80
      # ----------------------------------------------------------------------------------------
      # REDIRECT has the following format:
      #     urltarget|redirection
      # For example, for REVPROXY=/planefinder/setup.html|http://10.0.0.191:8086/setup.html,
      # a user browing to http://mydomain/planefinder/setup.html will be redirected to http://10.0.0.191:8086/setup.html
      # The user's browser will show the redirection address and try to reach it. If the destination is not reachable (for example
      # because it is on a isolated subnet), the browser won't be able to render the page.
      # This can be useful if you want to protect certain pages from view outside your internal network, while exposing
      # others. See for example the planefinder setup in REVPROXY and REDIRECT.
      # Note - both the urltarget and the redirection MAY BE a URL or a file names.
      - REDIRECT=
                 /planefinder/setup.html|http://10.0.0.191:8086/setup.html,
                 /planefinder/logs.html|http://10.0.0.191:8086/logs.html
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,relatime,size=128M
    volumes:
      - /home/pi/.revproxy:/run/revproxy
#
# Special handling:
# REVPROXY for "acarshub" will automatically configure the following additional parameters:
#        proxy_set_header Upgrade $http_upgrade;
#        proxy_set_header Connection $http_connection;
#        proxy_set_header Host $http_host;
#
# For PlaneFinder to work, you must also redirect "/ajax" to "http://planefinderurl/ajax"
# For the Readsb Graphs shortcut to work, you must also redirect "/radar" to "http://readsburl/radar"
